export default {
  "website": {
    "name": "TechInsights",
    "url": "https://techinsights.com",
    "description": "Your daily dose of technology news and insights",
    "language": "en",
    "categories": ["Technology", "AI", "Programming", "Gadgets", "Startups"]
  },

  "users": [
    {
      "id": 1,
      "username": "tech_guru",
      "email": "john.doe@email.com",
      "full_name": "John Doe",
      "avatar": "https://techinsights.com/avatars/john_doe.jpg",
      "role": "admin",
      "join_date": "2023-01-15",
      "last_login": "2024-01-20T10:30:00Z"
    },
    {
      "id": 2,
      "username": "code_wizard",
      "email": "sarah.smith@email.com",
      "full_name": "Sarah Smith",
      "avatar": "https://techinsights.com/avatars/sarah_smith.jpg",
      "role": "author",
      "join_date": "2023-03-22",
      "last_login": "2024-01-20T08:15:00Z"
    },
    {
      "id": 3,
      "username": "ai_enthusiast",
      "email": "mike.chen@email.com",
      "full_name": "Mike Chen",
      "avatar": "https://techinsights.com/avatars/mike_chen.jpg",
      "role": "subscriber",
      "join_date": "2023-06-10",
      "last_login": "2024-01-19T16:45:00Z"
    }
  ],

  "articles": [
    {
      "id": 101,
      "title": "The Future of Artificial Intelligence in 2024",
      "slug": "future-artificial-intelligence-2024",
      "excerpt": "Exploring the latest trends and predictions for AI development in the coming year.",
      "content": "Artificial intelligence continues to evolve at an unprecedented pace...",
      "author_id": 2,
      "author_name": "Sarah Smith",
      "category": "AI",
      "tags": ["AI", "Machine Learning", "Future Tech"],
      "published_date": "2024-01-15T09:00:00Z",
      "updated_date": "2024-01-16T14:30:00Z",
      "featured_image": "https://techinsights.com/images/ai-future.jpg",
      "status": "published",
      "views": 1250,
      "likes": 89,
      "comments_count": 23,
      "contentType": "article"
    },
    {
      "id": 102,
      "title": "Top Programming Languages to Learn in 2024",
      "slug": "top-programming-languages-2024",
      "excerpt": "A comprehensive guide to the most in-demand programming languages this year.",
      "content": "As technology evolves, so do the programming languages that power it...",
      "author_id": 1,
      "author_name": "John Doe",
      "category": "Programming",
      "tags": ["Programming", "Development", "Careers"],
      "published_date": "2024-01-10T11:00:00Z",
      "updated_date": "2024-01-10T11:00:00Z",
      "featured_image": "https://techinsights.com/images/programming-languages.jpg",
      "status": "published",
      "views": 980,
      "likes": 67,
      "comments_count": 15,
      "contentType": "blog"
    },
    {
      "id": 103,
      "title": "Review: Latest Smartphone Innovations",
      "slug": "review-latest-smartphone-innovations",
      "excerpt": "Hands-on review of the newest smartphone features and technologies.",
      "content": "The smartphone market continues to surprise us with innovative features...",
      "author_id": 2,
      "author_name": "Sarah Smith",
      "category": "Gadgets",
      "tags": ["Smartphones", "Review", "Mobile Tech"],
      "published_date": "2024-01-05T15:30:00Z",
      "updated_date": "2024-01-07T10:15:00Z",
      "featured_image": "https://techinsights.com/images/smartphone-review.jpg",
      "status": "published",
      "views": 750,
      "likes": 45,
      "comments_count": 12,
      "contentType": "article"
    },
    {
      "id": 104,
      "title": "Cloud Computing Trends: What's Next for AWS, Azure, and GCP",
      "slug": "cloud-computing-trends-2024",
      "excerpt": "Analyzing the future of cloud infrastructure and services.",
      "content": "Cloud computing continues to reshape how businesses operate...",
      "author_id": 1,
      "author_name": "John Doe",
      "category": "Technology",
      "tags": ["Cloud", "AWS", "Azure", "GCP", "Infrastructure"],
      "published_date": "2024-01-18T08:00:00Z",
      "updated_date": "2024-01-18T08:00:00Z",
      "featured_image": "https://techinsights.com/images/cloud-computing.jpg",
      "status": "published",
      "views": 890,
      "likes": 56,
      "comments_count": 18,
      "contentType": "blog"
    },
    {
      "id": 105,
      "title": "The Rise of Quantum Computing: Practical Applications",
      "slug": "quantum-computing-applications",
      "excerpt": "How quantum computing is moving from theory to real-world solutions.",
      "content": "Quantum computing represents a paradigm shift in computational power...",
      "author_id": 2,
      "author_name": "Sarah Smith",
      "category": "Technology",
      "tags": ["Quantum", "Computing", "Innovation"],
      "published_date": "2024-01-12T14:20:00Z",
      "updated_date": "2024-01-13T09:45:00Z",
      "featured_image": "https://techinsights.com/images/quantum-computing.jpg",
      "status": "published",
      "views": 1120,
      "likes": 78,
      "comments_count": 22,
      "contentType": "article"
    },
    {
      "id": 106,
      "title": "Cybersecurity Best Practices for Remote Work",
      "slug": "cybersecurity-remote-work",
      "excerpt": "Essential security measures for distributed teams.",
      "content": "With the rise of remote work, cybersecurity has never been more critical...",
      "author_id": 3,
      "author_name": "Mike Chen",
      "category": "Technology",
      "tags": ["Security", "Remote Work", "Cybersecurity"],
      "published_date": "2024-01-08T10:00:00Z",
      "updated_date": "2024-01-09T16:30:00Z",
      "featured_image": "https://techinsights.com/images/cybersecurity.jpg",
      "status": "published",
      "views": 950,
      "likes": 63,
      "comments_count": 14,
      "contentType": "article"
    },
    {
      "id": 107,
      "title": "Blockchain Beyond Cryptocurrency: Real-World Use Cases",
      "slug": "blockchain-real-world-use-cases",
      "excerpt": "Exploring practical applications of blockchain technology.",
      "content": "Blockchain technology offers far more than just cryptocurrency...",
      "author_id": 1,
      "author_name": "John Doe",
      "category": "Technology",
      "tags": ["Blockchain", "Innovation", "Decentralized"],
      "published_date": "2024-01-22T13:15:00Z",
      "updated_date": "2024-01-22T13:15:00Z",
      "featured_image": "https://techinsights.com/images/blockchain.jpg",
      "status": "published",
      "views": 780,
      "likes": 49,
      "comments_count": 11,
      "contentType": "article"
    },
    {
      "id": 108,
      "title": "The Evolution of Web Development Frameworks",
      "slug": "web-development-frameworks-evolution",
      "excerpt": "From jQuery to React: how web frameworks have changed.",
      "content": "Web development has undergone a dramatic transformation over the years...",
      "author_id": 2,
      "author_name": "Sarah Smith",
      "category": "Programming",
      "tags": ["Web Development", "Frameworks", "JavaScript"],
      "published_date": "2024-01-14T11:45:00Z",
      "updated_date": "2024-01-15T08:20:00Z",
      "featured_image": "https://techinsights.com/images/web-frameworks.jpg",
      "status": "published",
      "views": 1020,
      "likes": 71,
      "comments_count": 19,
      "contentType": "article"
    },
    {
      "id": 109,
      "title": "IoT Devices: Smart Home Revolution",
      "slug": "iot-smart-home-revolution",
      "excerpt": "How IoT is transforming our living spaces.",
      "content": "The Internet of Things has made our homes smarter and more connected...",
      "author_id": 3,
      "author_name": "Mike Chen",
      "category": "Gadgets",
      "tags": ["IoT", "Smart Home", "Automation"],
      "published_date": "2024-01-17T09:30:00Z",
      "updated_date": "2024-01-18T14:00:00Z",
      "featured_image": "https://techinsights.com/images/iot-smart-home.jpg",
      "status": "published",
      "views": 840,
      "likes": 52,
      "comments_count": 16,
      "contentType": "blog"
    },
    {
      "id": 110,
      "title": "Data Science Career Path: Skills and Opportunities",
      "slug": "data-science-career-path",
      "excerpt": "Your guide to building a career in data science.",
      "content": "Data science continues to be one of the most sought-after career paths...",
      "author_id": 1,
      "author_name": "John Doe",
      "category": "Programming",
      "tags": ["Data Science", "Career", "Machine Learning"],
      "published_date": "2024-01-19T15:00:00Z",
      "updated_date": "2024-01-19T15:00:00Z",
      "featured_image": "https://techinsights.com/images/data-science.jpg",
      "status": "published",
      "views": 1100,
      "likes": 82,
      "comments_count": 25,
      "contentType": "article"
    },
    {
      "id": 111,
      "title": "5G Technology: Impact on Mobile Connectivity",
      "slug": "5g-technology-impact",
      "excerpt": "How 5G is revolutionizing mobile internet speeds and capabilities.",
      "content": "The rollout of 5G technology promises to transform mobile connectivity...",
      "author_id": 2,
      "author_name": "Sarah Smith",
      "category": "Technology",
      "tags": ["5G", "Mobile", "Connectivity"],
      "published_date": "2024-01-21T10:20:00Z",
      "updated_date": "2024-01-21T10:20:00Z",
      "featured_image": "https://techinsights.com/images/5g-technology.jpg",
      "status": "published",
      "views": 920,
      "likes": 58,
      "comments_count": 17,
      "contentType": "article"
    },
    {
      "id": 112,
      "title": "UX Design Principles for Modern Applications",
      "slug": "ux-design-principles",
      "excerpt": "Essential UX guidelines for creating user-friendly applications.",
      "content": "User experience design has become crucial for application success...",
      "author_id": 3,
      "author_name": "Mike Chen",
      "category": "Programming",
      "tags": ["UX", "Design", "User Experience"],
      "published_date": "2024-01-16T12:00:00Z",
      "updated_date": "2024-01-17T09:15:00Z",
      "featured_image": "https://techinsights.com/images/ux-design.jpg",
      "status": "published",
      "views": 760,
      "likes": 47,
      "comments_count": 13,
      "contentType": "article"
    },
    {
      "id": 113,
      "title": "Startup Funding Rounds: Series A to IPO",
      "slug": "startup-funding-rounds",
      "excerpt": "Understanding the different stages of startup financing.",
      "content": "Navigating the complex world of startup funding can be challenging...",
      "author_id": 1,
      "author_name": "John Doe",
      "category": "Startups",
      "tags": ["Startups", "Funding", "VC", "Investment"],
      "published_date": "2024-01-23T08:45:00Z",
      "updated_date": "2024-01-23T08:45:00Z",
      "featured_image": "https://techinsights.com/images/startup-funding.jpg",
      "status": "published",
      "views": 680,
      "likes": 41,
      "comments_count": 9,
      "contentType": "blog"
    }
  ],

  "comments": [
    {
      "id": 1001,
      "article_id": 101,
      "user_id": 3,
      "user_name": "Mike Chen",
      "content": "Great article! I'm particularly excited about the advancements in natural language processing.",
      "created_date": "2024-01-15T14:20:00Z",
      "likes": 5,
      "status": "approved"
    },
    {
      "id": 1002,
      "article_id": 101,
      "user_id": 2,
      "user_name": "Sarah Smith",
      "content": "Thanks for your feedback! NLP is indeed a fascinating field with huge potential.",
      "created_date": "2024-01-15T15:10:00Z",
      "likes": 3,
      "status": "approved"
    },
    {
      "id": 1003,
      "article_id": 102,
      "user_id": 3,
      "user_name": "Mike Chen",
      "content": "I would add Rust to this list - it's gaining a lot of traction in systems programming.",
      "created_date": "2024-01-10T13:45:00Z",
      "likes": 8,
      "status": "approved"
    }
  ],

  "media": [
    {
      "id": 201,
      "type": "image",
      "url": "https://techinsights.com/images/ai-future.jpg",
      "alt_text": "Artificial Intelligence Concept Art",
      "upload_date": "2024-01-14T16:00:00Z",
      "size": "1200x800",
      "file_size": "450KB"
    },
    {
      "id": 202,
      "type": "image",
      "url": "https://techinsights.com/images/programming-languages.jpg",
      "alt_text": "Programming Languages Comparison",
      "upload_date": "2024-01-09T10:30:00Z",
      "size": "1000x600",
      "file_size": "320KB"
    },
    {
      "id": 203,
      "type": "video",
      "url": "https://techinsights.com/videos/smartphone-demo.mp4",
      "title": "Smartphone Features Demo",
      "duration": "5:30",
      "upload_date": "2024-01-04T14:20:00Z",
      "file_size": "45MB"
    }
  ],

  "api_info": {
    "version": "1.2.0",
    "documentation": "https://techinsights.com/api/docs",
    "rate_limit": "1000 requests per hour",
    "endpoints": {
      "articles": "/api/v1/articles",
      "users": "/api/v1/users",
      "comments": "/api/v1/comments",
      "media": "/api/v1/media",
      "search": "/api/v1/search"
    },
    "authentication": "Bearer token required for write operations"
  },

  "pagination": {
    "current_page": 1,
    "total_pages": 5,
    "items_per_page": 10,
    "total_items": 47,
    "next_page": "https://techinsights.com/api/v1/articles?page=2",
    "prev_page": null
  },

  "metadata": {
    "generated_at": "2024-01-20T12:00:00Z",
    "request_id": "req_abc123def456",
    "response_time": "45ms"
  }
};
